project:
  type: website

website:
  title: "world-book"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - content.qmd
  sidebar: 
    - id: content
      title: "Content"
      contents:
        - href: content.qmd
        - href: group-a.qmd
        - href: group-b.qmd
        - href: group-c.qmd
        - href: group-d.qmd
        - href: group-e.qmd
        - href: group-f.qmd
        - href: group-g.qmd
        - href: group-h.qmd

  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

